---
#Doesn't work with vagrant
#http://superuser.com/questions/991711/vagrant-virtualbox-doesnt-setup-correct-gateway
#- include_tasks: hosts.yml
- include_tasks: apt-proxy.yml
- include_tasks: upload-keyfile.yml
  when: keyFile is defined
