---
- name: install haproxy
  apt: name={{item}} state=present install_recommends=no update_cache=yes cache_valid_time=86400
  with_items:
  - haproxy

- name: configure haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: enable haproxy
  systemd: name=haproxy enabled=yes

- name: ensure haproxy is running
  service: name=haproxy enabled=yes state=started
